services:
  - type: web
    name: robotech-backend
    env: java
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/robotech-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://nozomi.proxy.rlwy.net:31381/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: jDPctEyjIUdViVmGrjxayJivIEhVQWUM
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SERVER_PORT
        value: "8080"